// @index('./*.js', f => `export * from '${f.path}'`)
export * from './all-elements-but-nth'
export * from './all-letters'
export * from './all-words'
export * from './average-of-elements-at-property'
export * from './elements-greater-than-10-at-property'
export * from './elements-less-than-100-at-property'
export * from './elements-that-equal-10-at-property'
export * from './even-length-words-at-property'
export * from './first-element-of-property'
export * from './index-of'
export * from './largest-element'
export * from './last-element-of-property'
export * from './length-of-longest-element'
export * from './length-of-shortest-element'
export * from './longest-element'
export * from './longest-of-three-words'
export * from './nth-element-of-property'
export * from './odd-length-words-at-property'
export * from './squared-elements-at-property'
// @endindex
